title:              2019NCOV
description:        Czym jest siódmy ludzki koronawirus?
author:             Filiio
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   princePhiliip

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
