title:              2019NCOV
description:        O koronawirusie 2019NCOV
author:             Filiio
baseurl:            "/"
url:                "https://2019ncov.filiio.site"

# Social Profiles
twitter_username:   princePhiliip

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
